# This Dockerfile creates the container for testing on openSUSE Tubleweed

FROM opensuse/tumbleweed
MAINTAINER Sergio Martins (sergio.martins@kdab.com)

RUN zypper -n update
RUN zypper -n install cmake ninja git-core llvm llvm-devel llvm-clang llvm-clang-devel libqt5-qtbase-devel libqt5-qtdeclarative-devel


