# SPDX-FileCopyrightText: Alexander Lohnau <alexander.lonau@gmx.de>
# SPDX-License-Identifier: CC0-1.0
Environment:
  KDECI_BUILD: "TRUE"
  CXX: "clang++"

Options:
  setup-dbus-session: False
  setup-x-environment: False
  require-passing-tests-on: ["@all"]
  per-test-timeout: 240 # Increase timeout, because some tests are parallelized in themselves and include really large headers
  tests-run-in-parallel: True
  cppcheck-arguments: "-i tests/"
